### ISSUE TITLE
Gestures without descriptions are not displayed in all cases

### ISSUE THREAD

**Issue by nvdaes** [grisov/checkGestures#2]
STR:

1. Install an add-on like [placeMarkers](https://github.com/nvdaes/placeMarkers)
2. In the source code of placeMarkers, go to some scripts like those used to open the bookmarks or specific search folder and place a # before the description word.
3. Save the add-on and restart NVDA.
4. Search for commands without description with Check Gestures add-on.

Expected:

The above scripts should be displayed in the dialog.

Actual:

They aren't displayed, but NVDA behavior is as expected since these commands cannot be assigned.

I think that NVDA's behavior is useful like that, so that we can assign commands for example to gestures that should be sent but not reassigned, useful to change the behavior of NVDA in apps with default gestures. So I think that this add-on should display these gestures since they maybe important for the user.

I've reviewed the add-on and, according to documentation, if I'm not wrong about this issue, for now user experience should be improved before posting it on the website, according to the current criteria followed by reviewers (this may change when the new process proposed by @feerrenrut is in place, not sure).
Thanks and let me know in case I'm missing something.

**Comment by grisov** [comment]
Hi Noelia,  

Please excuse me for the delay with the answer.  
Unfortunately, I can't reproduce the problem you described.  

The steps that I followed:  

1. Clone the repository of the add-on [placeMarkers](https://github.com/nvdaes/placeMarkers)
2. Run **scons** command in the root of the repo and install the generated add-on.
3. In the source code of placeMarkers, I consistently go to the following scripts and place a `#` before the `description` word:
    - script_specificFind()
    - script_activateNotesDialog()
    - script_saveBookmark()
    - script_deleteBookmark()
    - script_selectNextBookmark()
    - script_selectPreviousBookmark()
4. After each change I saved the add-on and restarted NVDA.
5. Search for commands without description with **Check Gestures** add-on. And each time the list included commands whose description had previously been hidden.

Sorry, but please could you try to reproduce this issue again?  
I am very grateful to you for your help in basic review of the add-on!  

p. s. By the way, running **scons** showed that the *buildVars.py* file didn't specify the version of the **PlaceMarkers** add-on.

**Comment by nvdaes** [comment]
Oh, I cannot reproduce the issue. No idea about the problem found before this. I don't know if it was related to a recent notification requesting a Windows update in my computer, updated few days ago. I had problems testing other program from source code, fixed when I updated the computer and restarted it.
I'll inform in the add-ons mailing list that I cannot reproduce the reported issue, so for me basic review pass.
If none raises objections, you can fork the nvaccess/addonFiles repo and make a pull request to post the add-on on the website.
@Josephsl or me can approve it requesting a review from NV Access, and NV Access may merge it.
You can see documentation of an add-on posted on the website like placeMarkers or others to see how to include the link to the stable or development version. You need to use a unique key for your add-on, ensuring it's not used by another one, for example, you may try to use  chig. See the [nvaccess/addonFiles](https://github.com/nvaccess/addonFiles) repo for more info an examples.

Of course, if you prefer that I create the pull request for you let me know, in case you need help. In this case, other collaborator may review the pull request created by me and request a review from NV Access.

PS: about scons, it's the expected behavior. I don't include the add-on version for releases, since GitHub Actions write it deppending on the used tag or the GitHub hash.

PS2: I have seen an interesting workflow used in this add-on to run mypy. I may use it with your permission for my add-ons if needed. ☺

Let's close the issue and I'll inform to the add-ons mailing list.

**Comment by grisov** [comment]
Great, Noelia, thank you for such detailed description!  
I will study the repository you mentioned and make a pull request to post this add-on on the comunity website!  

Regarding workflows for GitHub Actions - I copied them all from your projects, or wrote based on your developments ☺
I am very grateful to you for the detailed instructions and examples - this prompted me to further study this very handy tool!

**Comment by nvdaes** [comment]
Thanks. Also, when the pull request is merged, we have to update the documentation on the website. If you aren't part of the translation team in Assembla, I can send the markdown file to the translations repo for you.

Have a nice day!

**Comment by grisov** [comment]
Oh thank you, that would be great!  
Have a nice day!
